### PR TITLE
Adam/initial modeling

### PR DESCRIPTION
**Pull request by adambushman**
## Description

I generated two models using the training data: 

1. penalized logistic regression (using an elastic net)
2. support vector machine

Both leveraged cross validation and included all possible features. 

## Results

Penalized regression achieved an AUC of ~0.72 while SVM achieved just 0.55 AUC.

## How to review

Open the "Adam Modeling.html" file in a browser to review the results

### CODE REVIEW

**Comment by adambushman** [comment]
Hi Georgia, I honestly forgot to resolve class imbalance. I'll work that into my code today and make another commit to this branch.

**Comment by adambushman** [comment]
I've resolved the class imbalance issues for both Penalized Regression and Support Vector Machines.

I had an odd phenomenon where cross-validated SVM was producing poor AUC (~0.56) but testing data gave an AUC of ~0.81. I think it's a problem with caret. I'm going to do my own cross validation, hyper-parameter tuning today if I have time.

**Comment by adambushman** [comment]
AUC is now consistent across cross-validation and final model testing! This can be reviewed when ready

**Review by aspendlo92 — DISMISSED** [review]
Glad to see we got the cross-validated SVM's AUC to match the final test model. It's interesting that many of those interaction terms turned out to be important, but didn't improve the AUC very much while greatly increasing model complexity (which could lead to overfitting). I suppose we can just leave them out, then, if they don't help our performance metrics.

**Review by aspendlo92 — DISMISSED** [review]
Submitting review again after resolving conflicts

**Review by aspendlo92 — DISMISSED** [review]
Submitting approval once again

**Review by aspendlo92 — COMMENTED** [review]
Approved

**Pull request merged**
